# Generated by Django 4.1.3 on 2022-11-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dev', models.CharField(max_length=255)),
                ('pub', models.CharField(max_length=255)),
                ('gen', models.CharField(max_length=255)),
                ('gtype', models.CharField(max_length=255)),
                ('syn', models.CharField(max_length=255)),
            ],
        ),
    ]
