# Generated by Django 4.1.3 on 2022-11-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
