# Generated by Django 4.1.3 on 2022-11-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='syn',
            field=models.TextField(),
        ),
    ]
