# Generated by Django 4.1.3 on 2022-12-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0003_alter_game_syn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='title_imgs'),
        ),
    ]
