# Generated by Django 4.1.3 on 2022-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0004_game_title_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sc1',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='game',
            name='sc2',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='game',
            name='sc3',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots'),
        ),
    ]
