# Generated by Django 4.1.3 on 2022-12-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0005_game_sc1_game_sc2_game_sc3'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='plat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='trailer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
