# Generated by Django 4.1.3 on 2022-12-09 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newgames', '0006_game_plat_game_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hype',
            field=models.ManyToManyField(related_name='new_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
