# Generated by Django 4.1.3 on 2022-12-09 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newgames', '0007_game_hype'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='meh',
            field=models.ManyToManyField(related_name='meh_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
