# Generated by Django 4.1.3 on 2022-12-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
    ]
