# Generated by Django 4.1.3 on 2022-12-29 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0011_rename_name_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='syn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
