# Generated by Django 4.1.4 on 2023-01-05 16:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0012_alter_game_syn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='game',
            name='plat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='sc1',
            field=models.ImageField(null=True, upload_to='screenshots'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sc2',
            field=models.ImageField(null=True, upload_to='screenshots'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sc3',
            field=models.ImageField(null=True, upload_to='screenshots'),
        ),
        migrations.AlterField(
            model_name='game',
            name='syn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title_img',
            field=models.ImageField(null=True, upload_to='title_imgs'),
        ),
        migrations.AlterField(
            model_name='game',
            name='trailer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
