# Generated by Django 4.1.4 on 2023-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgames', '0013_alter_comment_options_alter_game_plat_alter_game_sc1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
